### ISSUE TITLE
Bug com IsCNPJ para CNPJ 39591842000010

### ISSUE THREAD

**Issue by jvcoutinho** [paemuri/brdoc#26]
A lib diz que esse CNPJ 39.591.842/0000-10 não é válido: https://go.dev/play/p/Xx2wSw8yfDe

Mas todos os outros sites, incluindo o da Receita, dizem que é:

<img width="1221" alt="image" src="https://github.com/paemuri/brdoc/assets/27645414/4fdfcd40-3606-4dfe-8e3f-cea40cb82559">

Pode ser um bug com o algoritmo.

**Comment by paemuri** [comment]
Primeiramente, obrigado pela contribuição e perdão pela demora! hehe

Sobre o seu caso... Mas isso é válido? Se não me engano, essa parte entre `/` e `-` (no caso, `0000`) que representa a filial é incremental e começa sempre com 1. Por exemplo, o CNPJ do Banco do Brasil, _o primeiro CNPJ do país_, é [`00.000.000/0001-91`](https://www.informecadastral.com.br/cnpj/banco-do-brasil-sa-00000000000191), e o teu exemplo não aparece no informecadastral.com.br.

Não sou o maior especialista no assunto, mas não me parece ser válido mesmo. :eyes: 

cc @tiagompalte por ter feito o PR (obrigado por isso).

**Comment by jvcoutinho** [comment]
@paemuri 

> Qual é essa página da Receita em que você testou?

Esse aqui: https://solucoes.receita.fazenda.gov.br/servicos/cnpjreva/Cnpjreva_Solicitacao.asp?cnpj=39591842000010

Quando o CNPJ é inválido, ele mostra a mensagem:

![image](https://github.com/paemuri/brdoc/assets/27645414/58ff6745-4825-424f-abde-6d9f2b5bd620)

Mas, para esse CNPJ, ele mostra a mensagem: 

![image](https://github.com/paemuri/brdoc/assets/27645414/1cad78ab-9fa4-4664-952a-690df926856e)

Que informa que ele é de fato válido, mas não pertence a nenhuma empresa no momento.

**Comment by paemuri** [comment]
Obrigado pela resposta, @jvcoutinho.

Ainda não consigo entender como uma filial `0000` pode ser válida. Pesquisarei sobre o assunto.

**Comment by paemuri** [comment]
Vou fechar esta issue porque realmente creio que não devamos permitir `0000` no sufixo. Toda referência que eu busco mostra como o sufixo _deve_ começar no `0001` (representando a matriz) e os valores sebsequentes (`0002`) representam filiais, como Wikipédia ([aqui](https://pt.wikipedia.org/wiki/Cadastro_Nacional_da_Pessoa_Jur%C3%ADdica#Formato)) e uma página da Sumup ([aqui](https://www.sumup.com/pt-br/comecar/cnpj/#qual-a-estrutura-do-cnpj)). Se em algum momento esta lib acabar barrando um CNPJ realmente sendo usado na prática, podemos reabri-lo.
De qualquer forma, agradeço pela ajuda, @jvcoutinho; e para @tiagompalte também, por tentar implementar uma solução.
